---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyapplication
  labels:
    app: flask
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: pyapplication
        image: syedsaadahmed2094/pyapplicationnew:v5
        #imagePullPolicy: Never
        env:
        - name: MYSQL_DB_HOST
          value: mysql
        - name: MYSQL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: mysql_password
        ports:
        - containerPort: 5000
          name: flask-container
---
apiVersion: v1
kind: Service
metadata:
  name: pyapplication
  labels:
    app: flask
spec:
  ports:
  - port: 5000
    protocol: TCP
    name: flask
  selector:
    app: flask
  type: LoadBalancer
...